// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBAnkXn4HQ2ZkwRiIiPsnK6B5gAjdnBKM',
    appId: '1:392541474361:web:d6591a224345b5a0de87e8',
    messagingSenderId: '392541474361',
    projectId: 'writerchinese-587e1',
    authDomain: 'writerchinese-587e1.firebaseapp.com',
    storageBucket: 'writerchinese-587e1.firebasestorage.app',
    measurementId: 'G-LKP6LD2C8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlgXinZQxPzDIEAJsQNbhTH-5cWRhUeTc',
    appId: '1:392541474361:android:34f4b8638bc41c32de87e8',
    messagingSenderId: '392541474361',
    projectId: 'writerchinese-587e1',
    storageBucket: 'writerchinese-587e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmQpAMl7yWbXh4-6MVK8kACQ5DsSD9hPQ',
    appId: '1:392541474361:ios:f15ec93df7dd3f0fde87e8',
    messagingSenderId: '392541474361',
    projectId: 'writerchinese-587e1',
    storageBucket: 'writerchinese-587e1.firebasestorage.app',
    iosBundleId: 'writechinsesimple',
  );

}